console.log('hello word Solid!');

// * algoritmo fibonacci - 1618034

/*
    * VANTAGEM / DESVANTAGEM do S.O.L.I.D:

     *VANTAGEM:
      * -CODIGO MODULAR
      * -CODIGO REUTILIZAVEL (D.R.Y - DON'T REPEAT YOURSELF )
      * -CODIGO TESTAVEL,BAIXO ACOMPLAMENTO
      * -BAIXO ACOPLAMENTO E ALTA COESÃO
      * -CODIGO EXPANSIVEL
      * -SEPARATION OF CONCERNS (SEPARAÇÃO DE CONCEITOS)
      * -FACIL MANUTENÇÃO
      * *
      * DESVANTAGEM:
      *
      *  -COMPLEXIDADE
      *  -QUANTIDADE DE CODIGO
      *  -TENHA CUIDADO COM :
      *  -YAGNI = YOU AREN'T GONNA NEED IT
      *  -KISS = KEEP IT SIMPLE,STUPID!
*/
